// Generated by CoffeeScript 1.10.0
(function() {
  var approot, gulp, mkdir;

  gulp = require('gulp');

  mkdir = require('mkdirp');

  approot = 'app';

  gulp.task('init', function(cb) {
    var coffee, doc, i, img, jade, len, mock, stylus, val, vender;
    jade = approot + '/src/jade';
    stylus = approot + '/src/stylus';
    coffee = approot + '/src/coffee';
    vender = approot + '/src/vender';
    img = approot + '/src/img';
    mock = approot + '/mock/';
    doc = [jade + "/layout", jade + "/module", stylus + "/module", stylus + "/font", coffee + "/lib", coffee + "/module", "" + vender, "" + img, "" + mock];
    for (i = 0, len = doc.length; i < len; i++) {
      val = doc[i];
      mkdir.sync(val);
    }
    return cb();
  });

  gulp.task('default', ['init']);

}).call(this);

//# sourceMappingURL=gulpfile.js.map
