// Generated by CoffeeScript 1.10.0

/* 数据格式演示
aqiSourceData =
  '北京':
    "2016-01-01": 10
    "2016-01-02": 10
    "2016-01-03": 10
    "2016-01-04": 10
 */

(function() {
  var aqiSourceData, chartData, citySelectChange, getDateStr, graTimeChange, init, initAqiChartData, initCitySelector, initGraTimeForm, pageState, randomBuildData, renderChart;

  getDateStr = function(dat) {
    var d, m, y;
    y = dat.getFullYear();
    m = dat.getMonth() + 1;
    if (m < 10) {
      m = '0' + m;
    }
    d = dat.getDate();
    if (d < 10) {
      d = '0' + d;
    }
    return y + '-' + m + '-' + d;
  };

  randomBuildData = function(seed) {
    var dat, datStr, i, j, returnData;
    returnData = {};
    dat = new Date("2016-01-01");
    datStr = '';
    for (i = j = 1; j <= 92; i = ++j) {
      datStr = getDateStr(dat);
      returnData[datStr] = Math.ceil(Math.random() * seed);
      dat.setDate(dat.getDate() + 1);
    }
    return returnData;
  };

  aqiSourceData = {
    "北京": randomBuildData(500),
    "上海": randomBuildData(300),
    "广州": randomBuildData(200),
    "深圳": randomBuildData(100),
    "成都": randomBuildData(300),
    "西安": randomBuildData(500),
    "福州": randomBuildData(100),
    "厦门": randomBuildData(100),
    "沈阳": randomBuildData(500)
  };

  chartData = {};

  pageState = {
    nowSelectCity: -1,
    nowGraTime: 'day'
  };

  renderChart = function() {};

  graTimeChange = function() {
    var timeType, types;
    timeType = '';
    types = document.getElementsByName('gra-time');
    [].forEach.call(types, function(value) {
      if (value.checked) {
        return timeType = value.value;
      }
    });
    if (timeType !== pageState.nowGraTime) {
      pageState.nowGraTime = timeType;
      initAqiChartData();
      return renderChart();
    }
  };

  citySelectChange = function() {};

  initGraTimeForm = function() {
    var types;
    types = document.getElementsByName("gra-time");
    return [].forEach.call(types, function(value) {
      return value.addEventListener("click", graTimeChange);
    });
  };

  initCitySelector = function() {};

  initAqiChartData = function() {};

  init = function() {
    initGraTimeForm();
    initCitySelector();
    return initAqiChartData();
  };

  init();

}).call(this);

//# sourceMappingURL=task17.js.map
