// Generated by CoffeeScript 1.10.0
(function() {
  var btn, display, input;

  input = document.getElementById("aqi-input");

  display = document.getElementById("aqi-display");

  btn = document.getElementById("button");

  btn.onclick = function() {};

  if (input.value.length > 0) {
    display.innerHTML = input.value;
  } else {
    display.innerHTML = "请输入";
  }

}).call(this);

//# sourceMappingURL=task13.js.map
